# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "StoryTime Productions Dev Blog"
email: brommitment@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the StoryTime Productions Dev Blog! Behind the screen insights from our game development journey in Montreal, Quebec. 
  We create immersive Unity games spanning horror, sci-fi, and arcade genres.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://storytime-productions.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: StoryTime-Productions

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Site logo and favicon
logo: "/assets/images/st-logo.png"
favicon: "/assets/images/favicon.svg"

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - blog/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

author:
  name   : "StoryTime Productions"
  avatar : "/assets/images/st-logo.png"
  bio    : "Indie game studio crafting immersive Unity experiences from Montreal. Students turned developers exploring horror, sci-fi & arcade genres. 🎮🇨🇦"
  location: "Montreal, Quebec, Canada"
  links:
    - label: "Portfolio"
      icon: "fas fa-fw fa-gamepad"
      url: "https://storytime-productions.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/StoryTime-Productions"
    - label: "Contact"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:brommitment@gmail.com"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/StoryTime-Productions"
    - label: "Portfolio"
      icon: "fas fa-fw fa-gamepad"
      url: "https://storytime-productions.github.io"
    - label: "Contact"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:brommitment@gmail.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
